import { Wesen } from "./wesen.js";
import { Tipo, Peligrosidad } from "./enums.js";

export const wesens = [
  new Wesen(
    "Blutbad",
    "../assets/blutbad.png",
    Tipo.Canido,
    Peligrosidad.Neutral,
    "Los Blutbaden son criaturas parecidas a los hombres lobo, pero no se transforman en lobos. Son muy fuertes y ágiles, y tienen una gran capacidad olfativa.",
    "Monroe es un Blutbad y es amigo de Nick, el protagonista de la serie.",
  ),
  new Wesen(
    "Fuchsbau",
    "../assets/fuchsbau.jpg",
    Tipo.Canido,
    Peligrosidad.Pacifico,
    "Los Fuchsbau son criaturas parecidas a los zorros, y son conocidos por su astucia y habilidades de manipulación.",
    "Rosalee es una Fuchsbau y trabaja como farmacéutica.",
  ),
  new Wesen(
    "Hexenbiest",
    "https://vignette.wikia.nocookie.net/grimm/images/2/2e/Adalind.jpg/revision/latest/scale-to-width-down/310?cb=20120114193459",
    Tipo.Monstruo,
    Peligrosidad.Peligroso,
    "Las Hexenbiest son criaturas mágicas con habilidades de brujería. Son conocidas por su belleza y su capacidad para lanzar hechizos.",
    "Adalind es una Hexenbiest y es uno de los principales antagonistas de la serie.",
  ),
  new Wesen(
    "Siegebarst",
    "../assets/siegebarst.jpeg",
    Tipo.Cerdo,
    Peligrosidad.Peligroso,
    "Los Siegebarst son criaturas parecidas a los cerdos, y son conocidos por su fuerza y resistencia. Pueden ser muy agresivos cuando se sienten amenazados.",
    "Sebastian es un Siegebarst y trabaja como carnicero.",
  ),
  new Wesen(
    "Mauvais Dentes",
    "../assets/mauvais.jpeg",
    Tipo.Lobo,
    Peligrosidad.Violento,
    "Los Mauvais Dentes son criaturas parecidas a los lobos, y son conocidos por su ferocidad y su capacidad para cazar en manada.",
    "Son uno de los Wesen más peligrosos y temidos.",
  ),
  new Wesen(
    "Hundjäger",
    "../assets/hundjager.jpeg",
    Tipo.Canido,
    Peligrosidad.Neutral,
    "Los Hundjäger son criaturas parecidas a los perros, y son conocidos por su lealtad y su habilidad para rastrear a sus presas.",
    "Son a menudo utilizados como cazadores y guardianes por otros Wesen.",
  ),
  new Wesen(
    "Wendigo",
    "../assets/wendigo.jpeg",
    Tipo.Monstruo,
    Peligrosidad.Violento,
    "Los Wendigos son criaturas parecidas a los caníbales, y son conocidos por su insaciable apetito por la carne humana. Son extremadamente peligrosos y difíciles de matar.",
    "Son considerados como una de las peores pesadillas de los Grimm.",
  ),
  new Wesen(
    "Bauerschwein",
    "../assets/bauerschwein.jpeg",
    Tipo.Cerdo,
    Peligrosidad.Pacifico,
    "Los Bauerschwein son criaturas parecidas a los cerdos, y son conocidos por su naturaleza trabajadora y su habilidad para transformarse en humanos.",
    "Son a menudo utilizados como mano de obra por otros Wesen.",
  ),
  new Wesen(
    "La Llorona",
    "../assets/llorona.jpeg",
    Tipo.Monstruo,
    Peligrosidad.Peligroso,
    "La Llorona es un espíritu vengativo que se cree que es el fantasma de una mujer que ahogó a sus hijos. Aparece como una mujer vestida de blanco que llora por sus hijos perdidos.",
    "Es uno de los Wesen más temidos y su historia es conocida en muchas culturas.",
  ),
  new Wesen(
    "Kehrseite-Schlich-Kennen",
    "../assets/kehrseite.jpeg",
    Tipo.Rata,
    Peligrosidad.Pacifico,
    "Los Kehrseite-Schlich-Kennen son criaturas parecidas a las ratas, y son conocidos por su naturaleza sigilosa y su habilidad para trepar por las paredes.",
    "Son a menudo utilizados como espías por otros Wesen.",
  ),
];
